// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufgrjuptapahksatjvtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmZ3JqdXB0YXBhaGtzYXRqdnRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzczMjg2NzEsImV4cCI6MjA5MjkwNDY3MX0._6_qpOtsg-_hAL5YWXKprI4Z3bmt1Q-UzqHpuRPlLdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});